package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/AmritRai1234/spine/pkg/manifest"
)

// MapFieldType converts Spine manifest field types to TypeScript type definitions.
func MapFieldType(fieldType string) string {
	switch strings.ToLower(strings.TrimSpace(fieldType)) {
	case "string", "str", "text":
		return "string"
	case "number", "float", "int", "integer":
		return "number"
	case "bool", "boolean":
		return "boolean"
	case "any", "":
		return "any"
	default:
		return "any"
	}
}

// toPascalCase converts EVENT_NAME or event_name to EventName.
func toPascalCase(s string) string {
	s = strings.ReplaceAll(s, "-", "_")
	s = strings.ReplaceAll(s, ".", "_")
	parts := strings.Split(s, "_")
	var result strings.Builder
	for _, p := range parts {
		if len(p) > 0 {
			result.WriteString(strings.ToUpper(p[:1]))
			result.WriteString(strings.ToLower(p[1:]))
		}
	}
	if result.Len() == 0 {
		return "Custom"
	}
	return result.String()
}

// GenerateTypeScript generates a complete, type-safe TypeScript module from a Spine manifest schema.
func GenerateTypeScript(schema *manifest.SpineSchema) string {
	var sb strings.Builder

	sb.WriteString("// Code generated by Spine CLI (spine codegen). DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf("// Spine Manifest Version: %d\n\n", schema.SpineVersion))

	// Collect unique event emits
	type eventDef struct {
		eventName string
		fields    []manifest.PayloadField
	}
	eventsMap := make(map[string][]manifest.PayloadField)
	statesMap := make(map[string][]manifest.PayloadField)

	for _, node := range schema.Nodes {
		for _, e := range node.Emits {
			if _, exists := eventsMap[e.Event]; !exists || len(e.Fields) > len(eventsMap[e.Event]) {
				eventsMap[e.Event] = e.Fields
			}
		}
		for _, l := range node.Listens {
			if _, exists := statesMap[l.State]; !exists || len(l.Fields) > len(statesMap[l.State]) {
				statesMap[l.State] = l.Fields
			}
		}
	}

	// Sort event keys for deterministic code generation
	var eventNames []string
	for name := range eventsMap {
		eventNames = append(eventNames, name)
	}
	sort.Strings(eventNames)

	var stateNames []string
	for name := range statesMap {
		stateNames = append(stateNames, name)
	}
	sort.Strings(stateNames)

	// Emit Payload Interfaces
	sb.WriteString("// ========================================================\n")
	sb.WriteString("// Event Payload Interfaces\n")
	sb.WriteString("// ========================================================\n\n")

	for _, evt := range eventNames {
		fields := eventsMap[evt]
		typeName := toPascalCase(evt) + "Payload"
		sb.WriteString(fmt.Sprintf("export interface %s {\n", typeName))
		if len(fields) == 0 {
			sb.WriteString("  [key: string]: any;\n")
		} else {
			for _, f := range fields {
				tsType := MapFieldType(f.FieldType)
				sb.WriteString(fmt.Sprintf("  %s: %s;\n", f.Name, tsType))
			}
		}
		sb.WriteString("}\n\n")
	}

	// Listen State Interfaces
	sb.WriteString("// ========================================================\n")
	sb.WriteString("// State Payload Interfaces\n")
	sb.WriteString("// ========================================================\n\n")

	for _, st := range stateNames {
		fields := statesMap[st]
		typeName := toPascalCase(st) + "State"
		sb.WriteString(fmt.Sprintf("export interface %s {\n", typeName))
		if len(fields) == 0 {
			sb.WriteString("  [key: string]: any;\n")
		} else {
			for _, f := range fields {
				tsType := MapFieldType(f.FieldType)
				sb.WriteString(fmt.Sprintf("  %s: %s;\n", f.Name, tsType))
			}
		}
		sb.WriteString("}\n\n")
	}

	// Event Payload Map
	sb.WriteString("// ========================================================\n")
	sb.WriteString("// Spine Event & State Mappings\n")
	sb.WriteString("// ========================================================\n\n")

	sb.WriteString("export interface EventPayloadMap {\n")
	if len(eventNames) == 0 {
		sb.WriteString("  [event: string]: Record<string, any>;\n")
	} else {
		for _, evt := range eventNames {
			typeName := toPascalCase(evt) + "Payload"
			sb.WriteString(fmt.Sprintf("  '%s': %s;\n", evt, typeName))
		}
	}
	sb.WriteString("}\n\n")

	// State Payload Map
	sb.WriteString("export interface StatePayloadMap {\n")
	if len(stateNames) == 0 {
		sb.WriteString("  [state: string]: Record<string, any>;\n")
	} else {
		for _, st := range stateNames {
			typeName := toPascalCase(st) + "State"
			sb.WriteString(fmt.Sprintf("  '%s': %s;\n", st, typeName))
		}
	}
	sb.WriteString("}\n\n")

	// Exported Type Unions
	sb.WriteString("export type SpineEvent = keyof EventPayloadMap;\n")
	sb.WriteString("export type SpineState = keyof StatePayloadMap;\n\n")

	// Helper Client Signature
	sb.WriteString("// Helper function type for type-safe event emissions\n")
	sb.WriteString("export type SpineEmitFunction = <E extends SpineEvent>(\n")
	sb.WriteString("  event: E,\n")
	sb.WriteString("  payload: EventPayloadMap[E]\n")
	sb.WriteString(") => Promise<{ status: string; event: E; emitted_states?: string[] }>;\n")

	return sb.String()
}
